---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ../svm-sources/svm-latex-ms.tex
title: "Anexo 2.4. Predicción de los datos CUIS"
#thanks: "Agradecimientos..."
author: 
- name: "Juan Carlos Martinez-Ovando"
- affiliation: ITAM
abstract: "Se presenta y comenta el codigo para implementar el procedimientos de identificación del estado de los hogares empleando el modelo de ingreso (MDI) propuesto."
#keywords: "..."
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
#spacing: double
#bibliography: C:/Users/jcmo/Dropbox/@BibTeX/ReferencesJCMO.bib
#biblio-style: apsr
endnote: yes
---

----------------

### Preambulo

```{r prelim, include=FALSE}
source("./Code/load.R.packages.R")
# Codigo
source("./Code/dald.R")
source("./Code/rald.R")
source("./Code/raldm.R")
source("./Code/pregald.R")
source("./Code/pred.blasso.mdi.R")
source("./Code/pred.bayesQR.mdi.R")
source("./Code/mdi.pred.R")
```

=========================================================

# Datos CUIS

```{r 01_BasesCuis}
# Datos CUIS
hogares_cuis_agr <- read.csv("../Bases.Cuis/hogares_cuis_agr.csv", header=TRUE)

colnames(hogares_cuis_agr)

hogares_cuis_agr$ENTIDAD <- hogares_cuis_agr$CVE_ENTIDAD_FEDERATIVA
hogares_cuis_agr$MUN <- hogares_cuis_agr$CVE_MUNICIPIO - 1000*hogares_cuis_agr$ENTIDAD
hogares_cuis_agr$LOC <- hogares_cuis_agr$CVE_LOCALIDAD - 10000000*hogares_cuis_agr$ENTIDAD - 10000*hogares_cuis_agr$MUN

colnames(hogares_cuis_agr)
```

# Datos MDI, localidades y lineas de bienestar

```{r 02_mdi_datos}
# Datos modelo
load("../Datos.Modelo/mdi_segmentacion.RData")
load("../Datos.Modelo/mdi_regresion.RData")

localidades <- read.csv("../Datos.Modelo/inegi_localidades.csv", 
                        header=TRUE)

lineas_bienestar <- read.csv("../Datos.Modelo/coneval_lineas_bienestar.csv",
                             header=TRUE)

hogares_cuis_agr <- as.data.frame(hogares_cuis_agr)
dim.hog.agr <- dim(hogares_cuis_agr)
dim.hog.agr
```

## Definición de tipos de variables

```{r 03_tipos_variables}
# Numeric 
#hogares_cuis_agr[,var_enighcuis_num] <- apply(hogares_cuis_agr[,var_enighcuis_num], as.numeric)

# Categorias
hogares_cuis_agr[,var_enighcuis_cat] <- lapply(hogares_cuis_agr[,var_enighcuis_cat], factor)

summary(hogares_cuis_agr)
```
```{r 04_caso_pred}
# Caso
j <- 1
caso <- as.data.frame(hogares_cuis_agr[j,])

# Prediccion (un caso a la vez)
caso.pred <- mdi.pred(caso,localidades,lineas_bienestar,
                      modelo_actual_rur,modelo_actual_urb, 
                      modelo_lm_rur,modelo_lm_urb,
                      modelo_qr_rur_lb,modelo_qr_urb_lb, 
                      modelo_qr_rur_lbm,modelo_qr_urb_lbm,
                      modelo_seg_rur,modelo_seg_rur_tab,
                      modelo_seg_urb,modelo_seg_urb_tab)
caso.pred
```

```{r 05_iteraciones}
# Iteraciones
j <- 2
for(j in 2:dim.hog.agr[1]){
#  print(j)
  # Seleccion del caso
  caso <- as.data.frame(hogares_cuis_agr[j,])
  # Prediccion
  caso.pred.new <- mdi.pred(caso,localidades,lineas_bienestar,
                            modelo_actual_rur,modelo_actual_urb, 
                            modelo_lm_rur,modelo_lm_urb,
                            modelo_qr_rur_lb,modelo_qr_urb_lb, 
                            modelo_qr_rur_lbm,modelo_qr_urb_lbm,
                            modelo_seg_rur,modelo_seg_rur_tab,
                            modelo_seg_urb,modelo_seg_urb_tab)
  # Agrupacion
  caso.pred <- rbind(caso.pred,caso.pred.new)
}
```


